// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/Huangkai1008/mall/internal/app/v1/account/repository"
	storage2 "github.com/Huangkai1008/mall/internal/app/v1/storage"
	"github.com/Huangkai1008/mall/internal/app/v1/storage/handler"
	"github.com/Huangkai1008/mall/internal/app/v1/storage/router"
	"github.com/Huangkai1008/mall/internal/app/v1/storage/service"
	"github.com/Huangkai1008/mall/internal/pkg/config"
	"github.com/Huangkai1008/mall/internal/pkg/provider/http"
	"github.com/Huangkai1008/mall/internal/pkg/provider/logging"
	"github.com/Huangkai1008/mall/internal/pkg/provider/registry"
	"github.com/Huangkai1008/mall/internal/pkg/provider/storage"
	"github.com/Huangkai1008/micro-kit/pkg/application"
	http2 "github.com/Huangkai1008/micro-kit/pkg/transport/http"
	"github.com/google/wire"
)

// Injectors from wire.go:

// CreateApp creates an app by wire.
func CreateApp(cf string) (*application.Application, error) {
	configConfig, err := config.New(cf)
	if err != nil {
		return nil, err
	}
	logger, err := logging.NewLogger(configConfig)
	if err != nil {
		return nil, err
	}
	client, err := storage.NewMinioClient(configConfig)
	if err != nil {
		return nil, err
	}
	storageService := service.NewService(configConfig, logger, client)
	storageHandler := handler.NewHandler(logger, storageService)
	group := router.NewStorageRouter(storageHandler)
	customValidator, err := http.NewValidator(configConfig)
	if err != nil {
		return nil, err
	}
	echo, err := http2.NewRouter(logger, group, customValidator)
	if err != nil {
		return nil, err
	}
	consulClient, err := registry.NewConsulClient(configConfig, logger)
	if err != nil {
		return nil, err
	}
	consulRegistry := registry.NewConsulRegistrar(consulClient)
	server := http.NewHTTPServer(configConfig, logger, echo, consulRegistry)
	applicationApplication, err := storage2.New(configConfig, logger, server, client)
	if err != nil {
		return nil, err
	}
	return applicationApplication, nil
}

// wire.go:

var providerSet = wire.NewSet(storage2.ProviderSet, config.ProviderSet, registry.ProviderSet, storage.ProviderSet, logging.ProviderSet, router.ProviderSet, http.ProviderSet, repository.ProviderSet, service.ProviderSet, handler.ProviderSet)
