openapi: 3.0.3
info:
  title: Account Service API
  description: This is the API for the Account Service.
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  version: 0.1.0
  contact:
    name: HuangKai
    url: 'https://github.com/Huangkai1008'
    email: h1770360848@outlook.com
servers:
  - url: 'http://localhost:5001/{basePath}'
    description: Development server
    variables:
      basePath:
        default: api/v1/accounts
paths:
  /:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
        description: ''
      description: 创建一个新的账户
      operationId: createAccount
      summary: 创建账户
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          $ref: '#/components/responses/400'
        '422':
          $ref: '#/components/responses/422'
    parameters: []
components:
  schemas:
    ObjectMeta:
      title: ObjectMeta
      x-stoplight:
        id: n7keb518hon7b
      type: object
      x-examples:
        example-1:
          id: 1
          create_time: '2019-08-24 14:15:22'
          update_time: '2019-08-24 14:15:22'
      properties:
        id:
          type: integer
          format: int64
          minimum: 0
          exclusiveMinimum: true
          example: 1
          description: 对象唯一标识符
          readOnly: true
        create_time:
          type: string
          format: date-time
          example: '2019-08-24 14:15:22'
          description: 对象的创建时间
          readOnly: true
        update_time:
          type: string
          format: date-time
          example: '2019-08-24 14:15:22'
          description: 对象的更新时间
          readOnly: true
      required:
        - id
        - create_time
        - update_time
    HTTPException:
      title: HTTPException
      x-stoplight:
        id: m90a9jstl039e
      type: object
      properties:
        message:
          type: string
          description: 错误信息
          readOnly: true
      required:
        - message
    Account:
      allOf:
        - $ref: '#/components/schemas/ObjectMeta'
        - type: object
          properties:
            username:
              type: string
              maxLength: 127
              description: 用户名
            email:
              type: string
              format: email
              maxLength: 127
              description: 邮箱
            password:
              type: string
              description: 密码
              format: password
              maxLength: 64
              writeOnly: true
          required:
            - username
            - email
            - password
      x-examples:
        example-1:
          id: 1
          create_time: '2019-08-24 14:15:22'
          update_time: '2019-08-24 14:15:22'
          username: string
          email: user@example.com
  responses:
    '400':
      description: Example response
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/HTTPException'
    '422':
      description: Example response
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/HTTPException'
