openapi: 3.0.3
info:
  title: "Account Service API"
  description: "This is the API for the Account Service."
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
  version: 0.1.0
servers:
  - url: http://localhost:5001/{basePath}
    description: Development server
    variables:
      basePath:
        default: /api/v1/accounts
paths:
  /:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountCreate'
      description: "创建一个新的账户"
      responses:
        "201":
          description: "创建新的账户成功"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        "422":
          $ref: '#/components/responses/422'
  
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
          description: 用户名
        email:
          type: string
          description: 邮箱
    AccountCreate:
      type: object
      properties:
        username:
          type: string
          description: 用户名
          maxLength: 127
        email:
          type: string
          description: 邮箱
          maxLength: 127
        password:
          type: string
          description: 密码
          format: password
          maxLength: 64
      required: [username, email, password]
  responses:
    422:
      $ref: '#/components/schemas/Error'
