openapi: 3.0.3
info:
  title: "Storage Service API"
  description: "This is the API for the Storage Service."
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
  version: 0.1.0
servers:
  - url: http://localhost:5001/{basePath}
    description: Development server
    variables:
      basePath:
        default: /api/v1/storage
paths:
  /objects:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectCreate'
      description: "上传文件到对象存储"
      responses:
        "201":
          description: "上传成功"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Object'
        "422":
          $ref: '#/components/responses/422'

components:
  schemas:
    Object:
      type: object
      properties:
        url:
          type: string
        etag:
          type: string
        last_modified:
          type: string
#        id:
#          type: integer
#        username:
#          type: string
#        email:
#          type: string
    ObjectCreate:
      type: object
      properties:
        file:
          type: string
          format: binary
      required: [file]
  responses:
    422:
      $ref: '#/components/schemas/Error'

