Version = '0.1.0'
RunMode = 'debug'
Locale = 'zh'

[log]
Level = 0
FileName = 'logs/mall.log'

[http]
HttpHost = '127.0.0.1'
HttpPort = 8000
ReadTimeout = 60
WriteTimeout = 60

[gorm]
MaxIdleConnections = 10
MaxOpenConnections = 100
EnableAutoMigrate = true